_target_: stable_ssl.JointEmbedding
objective:
  _target_: stable_ssl.NTXEntLoss
  temperature: 0.5
networks:
  backbone:
    _target_: stable_ssl.utils.load_backbone
    name: resnet18
    dataset: "CIFAR10"
  projector:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torch.nn.Linear
        in_features: 512
        out_features: 2048
        bias: False
      - _target_: torch.nn.BatchNorm1d
        num_features: ${trainer.networks.projector._args_.0.out_features}
      - _target_: torch.nn.ReLU
      - _target_: torch.nn.Linear
        in_features: ${trainer.networks.projector._args_.0.out_features}
        out_features: 128
        bias: False
  projector_classifier:
    _target_: torch.nn.Linear
    in_features: 128
    out_features: ${trainer.data._num_classes}
  backbone_classifier:
    _target_: torch.nn.Linear
    in_features: 512
    out_features: ${trainer.data._num_classes}