[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "stable-ssl"
description = "Self-Supervised Learning Library"
authors = [
    {name = "Randall Balestriero", email = "randallbalestriero@gmail.com"},
    {name = "Hugues Van Assel", email = "vanasselhugues@gmail.com"},
]
license = {text = "MIT"}
readme = {file = "README.md", content-type = "text/markdown"}
dependencies = [
    "numpy", 
    "torch",
    "torchvision", 
    "tqdm", 
    "omegaconf", 
    "wandb", 
    "hydra-core", 
    "hydra-submitit-launcher", 
    "pandas", 
    "jsonlines", 
    "torchmetrics", 
    "scipy",
]

dynamic = ["version"]

[tool.setuptools]
packages = ["stable_ssl"]

[tool.setuptools.dynamic]
version = {attr = "stable_ssl.__about__.__version__"}

[project.optional-dependencies]
test = [
    "pytest",
    "flake8",
    "coverage",
    "numpydoc",
    "pytest-cov",
    "codecov"
]

doc = [
    "sphinx",
    "sphinx-gallery",
    "sphinx-book-theme",
    "matplotlib",
    "numpydoc",
    "memory_profiler",
    "myst-parser",
    "pydocstyle",
]
