# @package _global_

trainer:
  logger:
    monitors:
      train:
        rankme:
          _target_: stable_ssl.monitors.RankMe
          limit: 12
          epsilon: 1e-7
        lidar:
          _target_: stable_ssl.monitors.LiDAR
          n: 128
