name: black-codestyle
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
    tags:
      - '**'

jobs:
  Black-Codestyle-Check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checking Out Repository
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Black
        run: pip install black
      - name: Run Black
        run: black --check .
